plugin: gcp_compute
regions:
  - europe-west2
projects:
  - coen-mahamed-ali
filters:
  - status = RUNNING
#  - networkInterfaces[0].network = projects/cloud-admin-vpc/global/networks/main-net
auth_kind: application
keyed_groups:
 # Create groups from GCE labels
  - prefix: gcp
    key: labels
hostnames:
  # List host by name instead of the default public ip
  - name
compose:
  ansible_host: networkInterfaces[0].networkIP
